#!/bin/bash

DATE=$(/bin/date +"%H:%M:%S--%d-%m-%Y")

###########################################################################
# Make sure to change VPNIFACE to match your VPN usage                    #
###########################################################################

VPNIFACE="ppp0"

# If no arguments are given, print this help
if [ -z "$*" ]; then echo "Use it with -a (--activate) or -c (--clear)"; fi

# Check if user wants to active or clear the killswitch 
for arg in "$@"
do
    if [ "$arg" == "--activate" ] || [ "$arg" == "-a" ]
    then
        echo "y" | /usr/bin/sudo /usr/sbin/ufw reset >> /tmp/VPN-Killswitch-Log-$DATE
        /usr/bin/sudo /usr/sbin/ufw default deny incoming >> /tmp/VPN-Killswitch-Log-$DATE
        /usr/bin/sudo /usr/sbin/ufw default deny outgoing >> /tmp/VPN-Killswitch-Log-$DATE
        /usr/bin/sudo /usr/sbin/ufw allow out on $VPNIFACE from any to any >> /tmp/VPN-Killswitch-Log-$DATE
        echo "y" | /usr/bin/sudo /usr/sbin/ufw enable >> /tmp/VPN-Killswitch-Log-$DATE
        echo "Killswitch has been enabled!"
    fi

    if [ "$arg" == "--clear" ] || [ "$arg" == "-c" ]
    then
        echo "y" | /usr/bin/sudo /usr/sbin/ufw reset >> /tmp/VPN-Killswitch-Log-$DATE
        /usr/bin/sudo /usr/sbin/ufw default deny incoming >> /tmp/VPN-Killswitch-Log-$DATE
        /usr/bin/sudo /usr/sbin/ufw default allow outgoing >> /tmp/VPN-Killswitch-Log-$DATE
        echo "y" | /usr/bin/sudo /usr/sbin/ufw enable >> /tmp/VPN-Killswitch-Log-$DATE
        echo "Killswitch has been cleared! Careful now ..."
    fi
done
